"""B0-D arm 1 — the `xtb --metadyn` conformer pipeline.

🔴 EVERY FIXTURE HERE IS REAL OUTPUT FROM THE VENDORED BINARY. `tests/fixtures/PROVENANCE.md`
   records the exact command, version and date. A fixture I invented would encode the xtb output I
   IMAGINE, and this session has already turned up two things about xtb's real output that nobody
   would have imagined:
     1. the success banner goes to STDERR, never stdout -- so a Python runner checking stdout
        concludes every run failed, silently, with rc=0 and every result file present;
     2. the run printed `thermostating problem` at 658 K against a requested 400 K and reported
        normal termination anyway.
   Both are in the fixture and both are asserted below.

🔴 R-4's SUBJECT MOVED. The batch now retires "does the xtb-metadyn route work", NOT "does the
   ETKDG route work". Tests assert the field names say so, because field names are what stop a
   write-up drifting back to a route that was withdrawn as undefined for this species class.
"""

import os
import unittest

import context  # noqa: F401
from sei_pilot import conformers, config, units

FIXTURES = os.path.join(context.REPO_ROOT, "tests", "fixtures")
TRJ = os.path.join(FIXTURES, "xtb_metadyn_li_ec_cation.trj")
INP = os.path.join(FIXTURES, "xtb_metadyn_li_ec_cation.inp")


def _trj():
    with open(TRJ) as fh:
        return fh.read()


class TestFixtureIsRealOutput(unittest.TestCase):
    def setUp(self):
        if not os.path.exists(TRJ):
            self.skipTest("fixture absent (running from the tarball)")

    def test_the_trajectory_is_the_one_the_vendored_binary_wrote(self):
        head = _trj().splitlines()[:2]
        self.assertEqual(head[0].strip(), "11")
        self.assertIn("xtb: 6.7.1", head[1],
                      "the fixture no longer carries the vendored binary's version stamp -- if it "
                      "was regenerated by something else, PROVENANCE.md is now wrong")

    def test_provenance_records_how_it_was_made(self):
        with open(os.path.join(FIXTURES, "PROVENANCE.md")) as fh:
            prov = fh.read()
        for token in ("--metadyn", "6.7.1", "thermostating problem", "STDERR"):
            self.assertIn(token, prov, "PROVENANCE.md no longer records %r" % token)


class TestMetadynInputIsTheDeckThatActuallyRan(unittest.TestCase):
    """🔴 The strongest check available on an input builder: byte-identity with a deck that ran."""

    def test_generated_deck_matches_the_fixture_deck(self):
        if not os.path.exists(INP):
            self.skipTest("fixture absent")
        with open(INP) as fh:
            real = fh.read()
        self.assertEqual(conformers.metadyn_input().strip(), real.strip(),
                         "the generated xcontrol deck no longer matches the one that produced "
                         "the fixture trajectory -- either a parameter moved in config, or the "
                         "builder drifted from a deck we know xtb accepts")

    def test_every_parameter_comes_from_config(self):
        """A hyperparameter written in code is a hyperparameter nobody reports."""
        cfg = config.load("b0_conformers.json")
        m = cfg["metadynamics"]
        deck = conformers.metadyn_input()
        for key, token in (("md_time_ps", "time="), ("md_temp_k", "temp="),
                           ("kpush", "kpush="), ("alp", "alp=")):
            self.assertIn("%s%s" % (token, m[key]), deck)

    def test_the_config_labels_the_parameters_as_unvalidated(self):
        """§37.2.3: the risk of re-implementing CREST is exactly these hyperparameters."""
        note = config.load("b0_conformers.json")["metadynamics"]["_parameter_source"]
        self.assertIn("CODER-CHOSEN", note)
        self.assertIn("NOT TUNED", note)

    def test_argv_uses_unpaired_electrons_not_multiplicity(self):
        """xtb's --uhf and Gaussian's multiplicity differ by one, and confusing them is silent."""
        self.assertEqual(conformers.uhf_from_multiplicity(1), 0)
        self.assertEqual(conformers.uhf_from_multiplicity(2), 1)
        self.assertRaises(ValueError, conformers.uhf_from_multiplicity, 0)
        argv = conformers.metadyn_argv("/x/xtb", "s.xyz", charge=1,
                                       uhf=conformers.uhf_from_multiplicity(1),
                                       input_path="i.inp")
        self.assertEqual(argv[argv.index("--uhf") + 1], "0")
        self.assertEqual(argv[argv.index("--chrg") + 1], "1")


class TestRunHealthIsNotTheBanner(unittest.TestCase):
    """🔴🔴 The trap measured on the real binary this session."""

    def _frames(self):
        return conformers.parse_trajectory(_trj())

    def setUp(self):
        if not os.path.exists(TRJ):
            self.skipTest("fixture absent")

    def test_absent_banner_in_stdout_does_not_make_a_good_run_a_failure(self):
        """🔴 xtb writes the banner to STDERR. Checking stdout fails EVERY run, silently."""
        h = conformers.xtb_health(stdout="...timings...", stderr="normal termination of xtb",
                                  returncode=0, frames=self._frames())
        self.assertTrue(h["usable"],
                        "a run with 20 parsed frames was called unusable because the success "
                        "banner was not in stdout -- it is never in stdout")
        self.assertTrue(h["banner_seen"], "the banner must be sought in BOTH streams")

    def test_a_present_banner_does_not_certify_a_run_with_no_frames(self):
        h = conformers.xtb_health(stdout="", stderr="normal termination of xtb",
                                  returncode=0, frames=[])
        self.assertFalse(h["usable"])
        self.assertTrue(h["banner_seen"])

    def test_the_thermostat_excursion_is_recorded_but_is_not_a_failure(self):
        h = conformers.xtb_health(stdout="T : 658.79\n thermostating problem\n",
                                  stderr="normal termination of xtb",
                                  returncode=0, frames=self._frames())
        self.assertTrue(h["usable"])
        self.assertIn("thermostating problem", h["soft_warnings"])
        self.assertIn("temperature the ensemble was sampled at", " ".join(h["warnings"]))

    def test_an_unusable_run_points_at_the_stream_trap_in_its_own_message(self):
        h = conformers.xtb_health(stdout="", stderr="", returncode=0, frames=[])
        self.assertIn("stderr", " ".join(h["warnings"]),
                      "an unusable verdict must name the stream trap, or the next person spends "
                      "the afternoon concluding that xtb is broken")

    def test_the_criterion_is_stated_in_the_output(self):
        h = conformers.xtb_health(frames=self._frames())
        self.assertIn("NOT the banner", h["criterion"])


class TestTrajectoryParsing(unittest.TestCase):
    def setUp(self):
        if not os.path.exists(TRJ):
            self.skipTest("fixture absent")
        self.frames = conformers.parse_trajectory(_trj())

    def test_all_twenty_frames_and_all_twenty_energies(self):
        self.assertEqual(len(self.frames), 20)
        self.assertEqual(sum(1 for f in self.frames if f["energy_hartree"] is not None), 20)

    def test_energies_are_hartree_and_converted_only_through_units(self):
        f = self.frames[0]
        self.assertAlmostEqual(f["energy_hartree"], -20.574765099713, places=9)
        self.assertAlmostEqual(f["energy_ev"], units.hartree_to_ev(f["energy_hartree"]),
                               places=9)

    def test_a_frame_with_an_unparseable_comment_is_kept_not_dropped(self):
        text = "3\nno energy here\nO 0 0 0\nH 1 0 0\nH 0 1 0\n"
        fr = conformers.parse_trajectory(text)
        self.assertEqual(len(fr), 1)
        self.assertIsNone(fr[0]["energy_hartree"],
                          "a frame that exists is evidence even when its energy did not parse")


class TestDissociationIsCountedNotDiscarded(unittest.TestCase):
    def setUp(self):
        if not os.path.exists(TRJ):
            self.skipTest("fixture absent")
        self.frames = conformers.parse_trajectory(_trj())

    def test_the_real_intact_frames_are_classified_intact(self):
        c = conformers.classify_complex(self.frames[0]["atoms"], n_ligands_expected=1)
        self.assertEqual(c["classification"], conformers.CLASS_INTACT)
        self.assertEqual(c["n_ligand_fragments"], 1)

    def test_a_dissociated_ligand_is_detected_and_named_as_such(self):
        atoms = self.frames[0]["atoms"]
        pulled = [(s, x, y + (25.0 if s == "Li" else 0.0), z) for s, x, y, z in atoms]
        c = conformers.classify_complex(pulled, n_ligands_expected=1)
        self.assertEqual(c["classification"], conformers.CLASS_DISSOCIATED)
        self.assertEqual(c["uncoordinated_fragments"], 1)

    def test_fragmentation_and_dissociation_are_different_classes(self):
        """🔴 A ligand that BROKE and a ligand that DRIFTED OFF mean different things."""
        atoms = self.frames[0]["atoms"]
        # Rip one hydrogen far away: the ligand is now two covalent fragments.
        broken = list(atoms)
        for i, a in enumerate(broken):
            if a[0] == "H":
                broken[i] = (a[0], a[1] + 12.0, a[2], a[3])
                break
        c = conformers.classify_complex(broken, n_ligands_expected=1)
        self.assertEqual(c["classification"], conformers.CLASS_FRAGMENTED)
        self.assertNotEqual(c["classification"], conformers.CLASS_DISSOCIATED)

    def test_a_structure_without_the_cation_is_unclassified_not_intact(self):
        """🔴 Rule 18: what cannot be classified is held out, never counted as intact."""
        no_li = [a for a in self.frames[0]["atoms"] if a[0] != "Li"]
        c = conformers.classify_complex(no_li, n_ligands_expected=1)
        self.assertIsNone(c["classification"])
        self.assertIn("classification_impossible", " ".join(c["warnings"]))

    def test_transient_stretches_in_the_real_trajectory_are_visible(self):
        """The real run has a frame at min(Li-X) = 2.688 A, past the 2.4 A contact cutoff.

        🔒 This is why classification runs on OPTIMISED structures, not raw MD frames -- and the
        number is asserted so the fixture cannot be swapped for a tamer one.
        """
        dmax = max(conformers.classify_complex(f["atoms"], 1)["min_contact_ang"]
                   for f in self.frames)
        self.assertGreater(dmax, 2.4,
                           "the fixture no longer contains a transient excursion past the "
                           "contact cutoff -- it was the reason for optimising before classifying")


class TestCutoffSensitivityIsReported(unittest.TestCase):
    """🔴 `layer_I.contact_cutoff_ang` is [PLACEHOLDER-ESTIMATE] and carries a MANDATORY rule."""

    def setUp(self):
        if not os.path.exists(TRJ):
            self.skipTest("fixture absent")
        self.structures = [f["atoms"] for f in conformers.parse_trajectory(_trj())]

    def test_the_sweep_runs_and_reports_flips_at_both_signs(self):
        s = conformers.sensitivity_sweep(self.structures, n_ligands_expected=1)
        self.assertEqual(s["n_structures"], 20)
        self.assertEqual(sorted(s["n_flipped"]), ["+0.20", "-0.20"])
        self.assertIn("intact", s["base_counts"])

    def test_the_placeholder_provenance_travels_with_the_number(self):
        s = conformers.sensitivity_sweep(self.structures, n_ligands_expected=1)
        self.assertIn("PLACEHOLDER-ESTIMATE", s["cutoff_provenance"] or "")
        self.assertIn("PLACEHOLDER-ESTIMATE", s["note"])


class TestRmsdAndDedupe(unittest.TestCase):
    def setUp(self):
        if not os.path.exists(TRJ):
            self.skipTest("fixture absent")
        self.frames = conformers.parse_trajectory(_trj())

    def test_rmsd_of_a_structure_with_itself_is_zero(self):
        a = self.frames[0]["atoms"]
        self.assertAlmostEqual(conformers.rmsd(a, a), 0.0, places=9)

    def test_rmsd_is_invariant_to_translation_and_rotation(self):
        """If it were not, dedupe would keep every frame and the ensemble would be meaningless."""
        import math
        a = self.frames[3]["atoms"]
        c, s = math.cos(0.9), math.sin(0.9)
        moved = [(sym, x * c - y * s + 7.0, x * s + y * c - 3.0, z + 11.0)
                 for sym, x, y, z in a]
        self.assertAlmostEqual(conformers.rmsd(a, moved), 0.0, places=6)

    def test_rmsd_of_genuinely_different_frames_is_not_zero(self):
        self.assertGreater(conformers.rmsd(self.frames[0]["atoms"],
                                           self.frames[10]["atoms"]), 0.05)

    def test_rmsd_refuses_mismatched_species_rather_than_returning_a_number(self):
        """🔴 It does NO atom matching. Silently comparing atom i with atom i would be worse."""
        a = self.frames[0]["atoms"]
        swapped = [a[1], a[0]] + list(a[2:])
        self.assertRaises(ValueError, conformers.rmsd, a, swapped)
        self.assertRaises(ValueError, conformers.rmsd, a, a[:-1])

    def test_dedupe_collapses_identical_structures(self):
        cands = [dict(self.frames[0], index=0), dict(self.frames[0], index=1)]
        unique, mapping = conformers.dedupe(cands)
        self.assertEqual(len(unique), 1)
        self.assertEqual(mapping["n_in"], 2)
        self.assertEqual(mapping["n_unique"], 1)

    def test_dedupe_keeps_distinct_structures(self):
        cands = [dict(self.frames[i], index=i) for i in (0, 5, 10, 15)]
        unique, _ = conformers.dedupe(cands)
        self.assertGreater(len(unique), 1)

    def test_dedupe_reports_its_hyperparameters_with_the_result(self):
        _, mapping = conformers.dedupe([dict(self.frames[0], index=0)])
        self.assertIn("rmsd_threshold_ang", mapping)
        self.assertTrue(mapping["_thresholds_are_coder_chosen"])

    def test_a_conformer_with_no_energy_is_never_silently_dropped(self):
        cands = [dict(self.frames[0], index=0),
                 {"index": 99, "atoms": self.frames[0]["atoms"], "energy_hartree": None}]
        unique, _ = conformers.dedupe(cands)
        self.assertIn(99, [u["index"] for u in unique],
                      "'we could not read its energy' is not 'it is a duplicate'")


class TestPromotionTakesTheWholeWindow(unittest.TestCase):
    """§37.2.4-2 — and it is what keeps this inside §16.1-B2."""

    def _cands(self, offsets_ev):
        base = -20.5
        return [{"index": i, "atoms": [("C", 0.0, 0.0, 0.0)],
                 "energy_hartree": base + units.ev_to_hartree(dE)}
                for i, dE in enumerate(offsets_ev)]

    def test_every_conformer_inside_the_window_is_promoted_not_just_the_lowest(self):
        sel = conformers.select_for_dft(self._cands([0.0, 0.05, 0.12, 0.30]))
        self.assertEqual(sel["n_selected"], 3,
                         "only the GFN2 minimum was promoted -- xTB is then setting the ΔG "
                         "ordering, which is what §37.2.4-2 exists to prevent")
        self.assertEqual(sel["window_ev"], 0.13)

    def test_the_window_boundary_is_inclusive_at_the_spec_value(self):
        sel = conformers.select_for_dft(self._cands([0.0, 0.13]))
        self.assertEqual(sel["n_selected"], 2)

    def test_the_output_says_the_ranking_belongs_to_dft(self):
        sel = conformers.select_for_dft(self._cands([0.0]))
        self.assertEqual(sel["rerank_at"], "dft")
        self.assertIn("16.1-B2", sel["_ordering_note"])

    def test_an_unscored_conformer_is_promoted_rather_than_dropped(self):
        cands = self._cands([0.0]) + [{"index": 9, "atoms": [("C", 0.0, 0.0, 0.0)],
                                       "energy_hartree": None}]
        sel = conformers.select_for_dft(cands)
        self.assertIn(9, [c["index"] for c in sel["selected"]])
        self.assertIn("not evidence that a conformer is high-lying", " ".join(sel["warnings"]))


class TestTemperatureIsTwoFieldsNeverOne(unittest.TestCase):
    """🔴 MD engines do not deliver the requested temperature, and the direction is engine-specific.

    Fixtures are three REAL runs differing only in the two variables under test. See
    tests/fixtures/PROVENANCE.md for the full decomposition.
    """

    def _trace(self, tag):
        path = os.path.join(FIXTURES, "xtb_T_trace_%s.txt" % tag)
        if not os.path.exists(path):
            self.skipTest("fixture absent")
        with open(path) as fh:
            return fh.read()

    def test_both_fields_are_emitted(self):
        r = conformers.temperature_report(400.0, self._trace("mtd_preoptimised"))
        self.assertEqual(r["temperature_requested_k"], 400.0)
        self.assertIsNotNone(r["temperature_measured_k"])
        self.assertNotEqual(r["temperature_requested_k"], r["temperature_measured_k"],
                            "requested and measured came out identical -- if a `temperature` "
                            "field is recording the setpoint, nobody will ever know")

    def test_the_thermostat_itself_is_correct(self):
        """🔴 THE FINDING. Plain MD from the optimised structure HOLDS ITS SETPOINT."""
        r = conformers.temperature_report(400.0, self._trace("plainmd"))
        self.assertLess(abs(r["temperature_measured_k"] - 400.0), 40.0,
                        "plain MD no longer holds its setpoint -- the conclusion that the "
                        "thermostat is correct rested on exactly this")
        self.assertEqual(r["warnings"], [])

    def test_the_bias_potential_is_what_raises_the_temperature(self):
        """Same optimised geometry, same $md block; the ONLY difference is $metadyn."""
        plain = conformers.temperature_report(400.0, self._trace("plainmd"))
        mtd = conformers.temperature_report(400.0, self._trace("mtd_preoptimised"))
        self.assertGreater(mtd["temperature_measured_k"] - plain["temperature_measured_k"], 50.0,
                           "the bias potential no longer shows a temperature effect -- the whole "
                           "diagnostic conclusion would need re-running")

    def test_the_idealised_start_adds_a_further_excursion_on_top(self):
        ideal = conformers.temperature_report(400.0, self._trace("mtd_idealised"))
        preopt = conformers.temperature_report(400.0, self._trace("mtd_preoptimised"))
        self.assertGreater(ideal["temperature_measured_k"], preopt["temperature_measured_k"],
                           "pre-optimising no longer reduces the temperature -- ADR-067's "
                           "'check the input first' would lose its instance here")

    def test_t_eff_is_not_a_constant(self):
        """🔴 It must be measured per run, never applied as a stored factor."""
        ratios = [conformers.temperature_report(400.0, self._trace(t))["t_eff_over_t_set"]
                  for t in ("mtd_idealised", "mtd_preoptimised", "plainmd")]
        self.assertGreater(max(ratios) - min(ratios), 0.3,
                           "the three conditions gave nearly the same T_eff/T_set, which would "
                           "make a stored factor defensible. It was 1.70 / 1.22 / 0.96.")

    def test_an_off_setpoint_metadynamics_run_is_flagged_but_not_called_a_defect(self):
        r = conformers.temperature_report(400.0, self._trace("mtd_idealised"))
        joined = " ".join(r["warnings"])
        self.assertIn("EXPECTED, not a defect", joined)
        self.assertIn("not a rate at a defined temperature", joined)

    def test_an_unparseable_log_says_the_temperature_is_unknown(self):
        r = conformers.temperature_report(400.0, "no md table here")
        self.assertIsNone(r["temperature_measured_k"])
        self.assertIn("temperature_not_measured", " ".join(r["warnings"]))


class TestSpecChangesFromTheThermostatRuling(unittest.TestCase):
    def setUp(self):
        self.cfg = config.load("b0_conformers.json")

    def test_arm1_pre_optimises_and_arm2_is_forbidden_from_it(self):
        pre = self.cfg["pre_optimisation"]
        self.assertTrue(pre["enabled"])
        self.assertIn("ARM 1 ONLY", pre["_doc"])
        self.assertIn("KEEPS ITS IDEALISED START", pre["_arm2_must_not_get_this"])

    def test_the_thermostat_finding_is_recorded_with_its_numbers(self):
        f = self.cfg["thermostat_finding"]["_measured"]
        self.assertEqual(f["setpoint_K"], 400.0)
        self.assertLess(abs(f["plain_md_from_optimised_K"] - 400.0), 40.0)
        self.assertGreater(f["mtd_from_optimised_K"], f["plain_md_from_optimised_K"])

    def test_the_wrong_prescription_is_recorded_so_it_is_not_reapplied(self):
        note = self.cfg["thermostat_finding"]["_the_prescription_that_would_have_been_wrong"]
        self.assertIn("demonstrably working", note)

    def test_the_dissociation_rate_consequence_is_routed_not_decided(self):
        note = self.cfg["thermostat_finding"]["_consequence_for_the_dissociation_rate"]
        self.assertIn("METHODOLOGY DECISION", note)
        self.assertIn("routed, not taken", note)

    def test_at_least_two_hyperparameter_pairs(self):
        """🔒 'CREST's wisdom is not a better pair -- it is using SEVERAL SIMULTANEOUSLY.'"""
        pairs = self.cfg["hyperparameter_pairs"]["pairs"]
        self.assertGreaterEqual(len(pairs), 2)
        self.assertNotEqual(pairs[0], pairs[1])
        self.assertGreaterEqual(len(self.cfg["hyperparameter_pairs"]["probe_species"]), 2)

    def test_the_stopping_rule_is_self_referential_not_a_fixed_time(self):
        """ADR-015 §1: an extensional boundary is answer-dependent and does not transfer."""
        sr = self.cfg["metadynamics"]["_stopping_rule"]
        self.assertIn("DISCOVERY RATE", sr["rule"])
        self.assertIn("max_time_ps", sr["rule"])
        self.assertIn("TRUNCATION LOOKS LIKE CONVERGENCE", sr["_cap_note"])

    def test_the_required_temperature_fields_are_declared(self):
        self.assertEqual(self.cfg["temperature_reporting"]["required_fields"],
                         ["temperature_requested_k", "temperature_measured_k"])


class TestThreeFiguresSurviveForR4(unittest.TestCase):
    def test_all_three_are_reported_separately(self):
        a = conformers.arm_comparison(arm1_ensemble_core_h=42.0, arm1_best_core_h=6.0,
                                      arm2_core_h=9.0, arm1_n_conformers=7)
        self.assertAlmostEqual(a["guess_penalty_ratio"], 1.5)
        self.assertAlmostEqual(a["conformer_search_cost_ratio"], 7.0)
        self.assertEqual(a["arm1_ensemble_core_h"], 42.0)
        self.assertEqual(a["arm1_best_core_h"], 6.0)
        self.assertEqual(a["arm2_core_h"], 9.0)

    def test_a_missing_input_gives_null_not_a_number(self):
        """C-1's discipline, applied to the ratios this arm exists to produce."""
        a = conformers.arm_comparison(None, 6.0, 9.0)
        self.assertIsNone(a["conformer_search_cost_ratio"])
        self.assertAlmostEqual(a["guess_penalty_ratio"], 1.5)
        b = conformers.arm_comparison(42.0, 0.0, 9.0)
        self.assertIsNone(b["conformer_search_cost_ratio"])

    def test_the_route_id_says_xtb_metadyn_and_never_etkdg(self):
        """🔴 R-4's subject moved with the route. Field names are what stop the drift."""
        a = conformers.arm_comparison(42.0, 6.0, 9.0)
        self.assertEqual(a["route"], "xtb_metadyn")
        self.assertIn("does NOT", a["_route_note"])
        self.assertIn("ETKDG", a["_route_note"],
                      "the note must NAME the withdrawn route, or a reader cannot tell that the "
                      "question moved")

    def test_the_output_forbids_collapsing_the_arms(self):
        a = conformers.arm_comparison(42.0, 6.0, 9.0)
        self.assertIn("ENSEMBLE", a["_do_not_collapse"])
        self.assertIn("ONE STRUCTURE", a["_do_not_collapse"])


if __name__ == "__main__":
    unittest.main()
